name = "mapkai"
compatibility_date = "2026-05-06"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "MAPKAI_DB"
database_name = "mapkai"
database_id = "842bbe82-191d-47a7-b6b6-59f5d0c98756"
