// Public, general-audience management learning overview.
globalThis.MAPKAI_MANAGEMENT_COLUMN = {
  title: "公司金融通识",
  titleEn: "Corporate Finance Essentials",
  subtitle: "给每一个想理解公司如何使用资金、承担风险与作出长期选择的人。",
  subtitleEn: "For anyone who wants to understand how companies use capital, carry risk, and make long-term choices.",
  description: "不需要金融背景。每天从一个真实的公司决定开始，用通俗语言看见价值、现金、风险、治理与下一步行动。",
  descriptionEn: "No finance background required. Each day starts with a real company decision and uses plain language to reveal value, cash, risk, governance, and a practical next move.",
  audiences: ["独立经营者", "职场学习者", "好奇的行动者"],
  audiencesEn: ["Independent operators", "Working learners", "Curious doers"],
  learningModules: [
    {
      id: "day-1-value-and-capital",
      day: "Day 1",
      title: "价值与资本配置",
      titleEn: "Value and Capital Allocation",
      summary: "一个看似有前景的计划，真的创造价值吗？它需要多少投入、何时回本、最坏会发生什么？",
      summaryEn: "Does a promising plan truly create value? What will it require, when will it pay back, and what can go wrong?",
      soloCompanyUse: "先判断一个新产品、渠道或 AI 工具是否真的创造价值，再决定投入、试行、等待或放弃。",
      soloCompanyUseEn: "Test whether a new product, channel, or AI tool truly creates value before deciding to invest, trial, wait, or walk away.",
      tags: ["现金流", "投入", "风险"],
      tagsEn: ["Cash flow", "Investment", "Risk"],
      audioTitle: "《第二张航海表》",
      audioTitleEn: "The Second Navigation Table",
      audioUrl: "https://media.turnpo.com/%E5%88%A9%E6%B6%A6%E8%83%8C%E5%90%8E%E7%9A%84%E7%94%9F%E6%AD%BB%E5%B1%80.m4a",
      audioUrlEn: "https://media.turnpo.com/day1-en.m4a",
    },
    {
      id: "day-2-trust-and-license",
      day: "Day 2",
      title: "信任与经营资格",
      titleEn: "Trust and the Licence to Operate",
      summary: "规则、承诺和透明度如何让客户、伙伴与市场愿意继续相信你？",
      summaryEn: "How can rules, promises, and transparency help customers, partners, and markets continue to trust you?",
      soloCompanyUse: "把承诺、数据来源、客户沟通与 AI 使用边界写清楚，避免增长建立在难以兑现的信任上。",
      soloCompanyUseEn: "Make promises, data sources, customer communication, and AI-use boundaries explicit, so growth is not built on trust you cannot keep.",
      tags: ["合规", "文化", "信任"],
      tagsEn: ["Compliance", "Culture", "Trust"],
      audioTitle: "《那张干净的检查表》",
      audioTitleEn: "The Clean Checklist",
      audioUrl: "https://media.turnpo.com/%E9%82%A3%E5%BC%A0%E5%B9%B2%E5%87%80%E7%9A%84%E6%A3%80%E6%9F%A5%E8%A1%A8.m4a",
      audioUrlEn: "https://media.turnpo.com/day2-en.m4a",
    },
    {
      id: "day-3-risk-and-governance",
      day: "Day 3",
      title: "事实、风险与治理",
      titleEn: "Facts, Risk, and Governance",
      summary: "怎样让关键事实和早期风险及时被看见，并在问题变大前有人行动？",
      summaryEn: "How can critical facts and early risks be seen in time, with someone acting before the problem grows?",
      soloCompanyUse: "为现金、交付、客户满意度和平台依赖设置少量可行动的信号；触线后有明确的下一步。",
      soloCompanyUseEn: "Set a few actionable signals for cash, delivery, customer satisfaction, and platform dependence; specify the next action when a threshold is crossed.",
      tags: ["证据", "风险", "责任"],
      tagsEn: ["Evidence", "Risk", "Responsibility"],
      audioTitle: "《披萨店后厨的三块白板》",
      audioTitleEn: "Three Whiteboards in a Pizza Kitchen",
      audioUrl: "https://media.turnpo.com/day-3-three-whiteboards.m4a",
      audioUrlEn: "https://media.turnpo.com/day3-en.m4a",
      storyTitle: "知识寓言｜《披萨店后厨的三块白板》",
      storyParagraphs: [
        "大学城旁边有一家小披萨店，叫“街角一块”。店里只有六张桌子，外卖却占了一半生意。每到周五晚上，订单打印机不停往外吐单子，老板阿明就觉得生意很好。",
        "三月底，他把账本带回家，对妻子说：“这个月不错，利润比去年同期高了三成。”妻子问：“披萨卖得更多了吗？”“没有，差不多。”阿明指着账本中的一行：店里以前有一辆旧送餐车，这个月卖了四千欧元。因为这辆车在账上的剩余价值已经很低，卖车带来的差额便成为当月的一笔收益。",
        "这笔利润是真的，但妻子继续问：“明年三月，我们还有一辆旧车可以卖吗？”阿明没有回答。",
        "第二天，他站在店里重新看了一圈。冷柜的门已经关不严，烤炉升温越来越慢。为了节省人工，周五晚班从四个人减成了三个人。披萨的销量没有增加，外卖平台上的差评却慢慢多了起来。这些问题都没有出现在“利润增长三成”那一行里。",
        "后来，阿明让店员小周做了一张风险表：烤炉故障是黄色，食材过期是黄色，员工临时请假和外卖延迟是红色，平台评分下降是黄色。小周把表贴在冷柜旁边。刚开始，大家经过时还会看一眼。几天后，上面又贴了排班表、旧菜单和饮料促销海报。慢慢地，没人再注意哪些项目已经变红。",
        "真正出事是在一个周五晚上。附近体育馆有比赛，订单一下子多了很多。一个员工临时请假，奶酪也只剩最后两包。烤炉连续工作几个小时后，温度开始不稳定。",
        "小周问：“超过多少单以后要关掉一个平台？”阿明说：“再看看。”十分钟后，小周又问：“堂食和外卖先做哪一个？”阿明说：“都别耽误。”这句话听起来像回答，其实什么也没有决定。",
        "到了晚上七点，有些披萨边缘已经烤焦，中间却还没有熟。客人开始催单，平台开始要求退款，前台和后厨都不知道谁可以暂停接单。那天晚上，他们退了二十多单，平台评分从 4.7 降到了 4.2。一个常来的学生写道：“披萨还是那个味道，但店里好像每个人都在忙，却没有人真正做决定。”",
        "第二天早上，阿明把冷柜旁边的海报、排班表和风险表全部取下来，在后厨挂上了三块白板。",
        "第一块白板上写着：“这个月到底是怎么赚的钱？”过去，阿明只看最后的利润数字。现在，他开始把数字拆开：披萨本身赚了多少，卖旧车赚了多少；哪些平台款还没有收到；哪些原料已经使用，但供应商账单还没有支付；哪些订单已经退款，不能继续算作收入。",
        "卖旧车带来的收益没有错，但它不能说明披萨生意本身变得更好。阿明第一次把两个问题分开：数字有没有记录正确？这些数字到底说明了什么？",
        "第二块白板上写着：“什么事情会让我们做不出合格的披萨？”这一次，风险后面不再只有红色、黄色和绿色。烤炉连续两次达不到设定温度，当天必须检查；奶酪只够一百张披萨时，前台停止促销；待完成订单超过四十单，值班店长可以暂停一个外卖平台；周五晚班少于四个人，不再接受大型团体订单；平台评分低于 4.5，第二天必须查看差评原因。",
        "阿明说：“颜色不是为了让表格看起来完整。颜色变化以后，必须有人改变做法。”",
        "第三块白板上写着：“谁可以做决定？”前台负责告诉客人真实的等待时间，并可以在规定范围内退款。后厨负责人决定食材能不能用、披萨能不能出餐。值班店长有权暂停接单，不需要等阿明亲自批准。小周每天关店前检查风险指标，但他不再只是负责更新颜色。阿明的妻子每周核对平台结算、供应商账单和店里的实际情况，检查账上的故事和店里的故事是否一致。",
        "接下来的两个月，账上的利润没有以前那么漂亮。卖旧车的收益不会再次出现。之前推迟的维修费进入了账目，退款也被扣除。为了保证周五晚班的人数，店里还增加了人工成本。阿明看着账本说：“这样一算，原来没有我想得那么好。”妻子回答：“至少现在，你知道问题在哪里。”",
        "几个月后，体育馆又有比赛。当待完成订单达到四十二单时，值班店长关闭了一个外卖平台。烤炉温度出现异常后，后厨暂停使用其中一层烤架，并重新告诉前台等待时间。那天晚上，他们少接了十几单。但没有出现大批退款，也没有新的差评。",
        "关店时，阿明说：“今晚少赚了一点。”值班店长笑着回答：“但明天还能继续开。”",
        "后来，阿明才知道，这三块白板在大公司里也有正式名称。第一块叫 Financial Accounting（财务会计），它帮助管理者看清已经发生的收入、成本、资产和义务，也帮助他们理解利润到底从哪里来。第二块叫 Enterprise Risk Management（企业风险管理，ERM），它帮助组织识别什么事情可能影响目标，并提前设定预警指标、行动界线和应对方法。第三块叫 Governance（治理），它让每个人知道谁负责经营、谁可以叫停、谁提出质疑，以及谁检查制度是否真的有效。",
        "阿明没有把这些英文词写进菜单。他只在三块白板下面写了一句话：“账上的好消息，要到店里看一遍；墙上的坏消息，要有人接下来处理。”",
      ],
      todayJudgement: "今天真正要学会的判断：先看清已经发生了什么；再理解数字背后的原因；再识别什么事情可能影响目标；再设定什么时候必须行动；最后说明谁负责决定、质疑和检查。先抓住三个问题：数字是否反映真实经营情况？什么事情可能影响组织目标？问题出现后，谁有责任和权力采取行动？",
    },
    {
      id: "day-4-strategy-and-action",
      day: "Day 4",
      title: "战略如何变成行为",
      titleEn: "How Strategy Becomes Behaviour",
      summary: "指标、预算和奖励会怎样改变人的注意力？又怎样避免数字反过来绑架真正的目标？",
      summaryEn: "How do metrics, budgets, and rewards change attention—and how can numbers avoid capturing the real goal?",
      soloCompanyUse: "用 AI 自动化之后，仍要保留对客户价值、学习质量与长期选择权的判断，而不只追逐效率数字。",
      soloCompanyUseEn: "After AI automation, retain judgement about customer value, learning quality, and long-term options instead of chasing efficiency numbers alone.",
      tags: ["KPI", "激励", "战略"],
      tagsEn: ["KPI", "Incentives", "Strategy"],
      audioTitle: "《第三勺红油》",
      audioTitleEn: "Why Accurate Metrics Sabotage Your Strategy",
      audioUrl: "https://media.turnpo.com/day-4-data-all-green.m4a",
      audioUrlEn: "https://media.turnpo.com/day4-en.m4a",
    },
    {
      id: "day-5-evidence-and-recommendation",
      day: "Day 5",
      title: "比较证据，形成建议",
      titleEn: "Compare Evidence, Form Advice",
      summary: "面对不完整的信息和看似漂亮的比较，怎样给出清楚、诚实、可质疑的建议？",
      summaryEn: "With incomplete information and attractive-looking comparisons, how can you give clear, honest, challengeable advice?",
      soloCompanyUse: "把 AI 给出的结论退回到证据、比较基准与适用条件，再决定是否采纳和如何行动。",
      soloCompanyUseEn: "Take AI-generated conclusions back to their evidence, benchmark, and conditions of use before deciding whether and how to act.",
      tags: ["比较", "判断", "建议"],
      tagsEn: ["Comparison", "Judgement", "Advice"],
      audioTitle: "《通过率最高的驾校》",
      audioTitleEn: "The Driving School with the Highest Pass Rate",
      audioUrl: "https://media.turnpo.com/%E4%B8%9A%E7%BB%A9%E6%A6%9C%E5%8D%95%E7%9A%84%E7%8C%AB%E8%85%BB.m4a",
      audioUrlEn: "https://media.turnpo.com/day5-en.m4a",
    },
  ],
  articles: [],
};
