import fs from "node:fs";
import path from "node:path";

const repoRoot = process.cwd();
const batchesDir = path.join(repoRoot, "content", "field-fables", "batches");
const outputPaths = [
  path.join(repoRoot, "content", "field-fables.js"),
  path.join(repoRoot, "public", "content", "field-fables.js"),
];

const batchFiles = fs.readdirSync(batchesDir)
  .filter((file) => /^batch-\d{3}\.json$/.test(file))
  .sort();

const articles = batchFiles.flatMap((file) => {
  const payload = JSON.parse(fs.readFileSync(path.join(batchesDir, file), "utf8"));
  return (payload.articles || [])
    .filter((article) => article.status === "approved")
    .map((article) => ({
      ...article,
      collection: "field-core-fables",
      storyBody: article.storyParagraphs.join("\n\n"),
      storyBodyZh: article.storyParagraphsZh.join("\n\n"),
      explanation: article.explanationParagraphs.join("\n\n"),
      explanationZh: article.explanationParagraphsZh.join("\n\n"),
    }));
});

const ids = new Set();
for (const article of articles) {
  if (ids.has(article.id)) throw new Error(`Duplicate approved field fable id: ${article.id}`);
  ids.add(article.id);
}

const output = `// Generated by tools/field-fables/build.mjs. Do not edit manually.\n` +
  `globalThis.MAPKAI_FIELD_CONCEPT_FABLES = ${JSON.stringify(articles, null, 2)};\n`;

for (const outputPath of outputPaths) {
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, output);
}

console.log(`Built ${articles.length} approved field fables into ${outputPaths.length} browser data files.`);
